"use strict";
var Definition_1 = require("./Definition");
var Definition_2 = require("./Definition");
var arg = require("./AlgorithmRGMethods");
// Some samples to test
console.log("Les utilisateurs:");
var ph = new Definition_1.User("PH");
var kribouille = new Definition_1.User("Benjamin");
var thain = new Definition_1.User("Alexandre");
var bastien = new Definition_1.User("Bastien");
console.log(ph);
console.log(kribouille);
console.log(thain);
console.log(bastien);
console.log("Les films:");
var ingloriousBasterds = new Definition_2.Movie("Inglorious Basterds", ["action", "drama"], ["c1", "c2", "c3", "c4", "c5"]);
var djangoUnchained = new Definition_2.Movie("Django Unchained", ["action", "comedy"], ["c1", "c2", "c3", "c4", "c5"]);
console.log(ingloriousBasterds);
console.log(djangoUnchained);
console.log("Les utilisateurs notent quelques films:");
var ph_ib = arg.rateMovie(ph, ingloriousBasterds, [1, 0, 1, 0, 1]);
var ph_du = arg.rateMovie(ph, djangoUnchained, [1, 0, 0, 0, 0]);
var ben_ib = arg.rateMovie(kribouille, ingloriousBasterds, [0, 0, 1, 1, 1]);
var thain_ib = arg.rateMovie(thain, ingloriousBasterds, [1, 1, 1, 0, 1]);
var bast_ib = arg.rateMovie(bastien, ingloriousBasterds, [1, 0, 1, 0, 1]);
console.log(ph_ib);
console.log(ph_du);
console.log(ben_ib);
console.log(thain_ib);
console.log(bast_ib);
console.log("Notre stub de bdd:");
var notreBdd = [ph_ib, ph_du, ben_ib, thain_ib, bast_ib];
console.log(notreBdd);
var allRatingOfIngBastExceptPH = arg.allInstancesOfThisRatedMovie(ingloriousBasterds, notreBdd, ph);
//console.log("Les utilisateurs ayant vu inglorious basterds sauf PH sont: " + allRatingOfIngBastExceptPH);
console.log("ça passe !");
var nonXORtableDePH = arg.sumNonXORuserObject(ph_ib, allRatingOfIngBastExceptPH);
nonXORtableDePH = arg.filterDescObject(nonXORtableDePH);
var firstTen = arg.getFirstTen(nonXORtableDePH);
console.log("First ten: ");
console.log(firstTen);
var allRecommendationsForPH = arg.allRecommendationsForU1(firstTen, notreBdd, ph);
console.log("Les recommendations pour PH: ");
console.log(allRecommendationsForPH);
console.log("ça passe !");
